### ISSUE TITLE
flash procedure error

### ISSUE THREAD

**Issue by adamvm** [charleskorn/stm32f4-project-template#2]
$ ./go.sh flash
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adi/dev/stm32f4-project-template/build/target
[ 95%] Built target stm32f4xx
[100%] Built target stm32f4test_firmware.elf
   text    data     bss     dec     hex filename
      0   72072       0   72072   11988 stm32f4test_firmware.elf
[100%] Built target stm32f4test_firmware.elf-size
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Error: open failed
in procedure 'program' 
in procedure 'init' called at file "embedded:startup.tcl", line 506
in procedure 'ocd_bouncer'
** OpenOCD init failed **
shutdown command invoked

make[3]: *** [main/CMakeFiles/flash_firmware.dir/build.make:57: main/CMakeFiles/flash_firmware] Błąd 1
make[2]: *** [CMakeFiles/Makefile2:258: main/CMakeFiles/flash_firmware.dir/all] Błąd 2
make[1]: *** [CMakeFiles/Makefile2:265: main/CMakeFiles/flash_firmware.dir/rule] Błąd 2
make: *** [Makefile:157: flash_firmware] Błąd 2

**Comment by charleskorn** [comment]
Hi @adamvm, I'm no longer actively maintaining this repo, but it looks like that's an issue with OpenOCD, so I'd recommend getting in touch with them.

**Comment by adamvm** [comment]
Thank you, if you just can point me to the place whera I can find in your scripts/Makefiles what are parameters that opeocd is called with. I scrol script and Makefile and till now without success

**Comment by charleskorn** [comment]
That's configured in CMake here: https://github.com/charleskorn/stm32f4-project-template/blob/1f4b1864572e1adbb8b9bfe6abe4462b509b3e1e/main/CMakeLists.txt#L23

**Comment by adamvm** [comment]
Strange thing that using 'make flash' from https://github.com/ahessling/STM32F4Template gives right effect:

make flash
[ 91%] Built target stm32f4xx
[100%] Built target STM32F4Template.elf
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Info : STLINK v2 JTAG v32 API v2 SWIM v0 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 2.899291
Info : stm32f4x.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
adapter speed: 1800 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08000374 msp: 0x20020000
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
adapter speed: 4000 kHz
** Programming Started **
auto erase enabled
Info : device id = 0x10016413
Info : flash size = 1024kbytes
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x20000046 msp: 0x20020000
wrote 16384 bytes from file STM32F4Template.elf in 0.541654s (29.539 KiB/s)
** Programming Finished **
** Resetting Target **
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
adapter speed: 1800 kHz
shutdown command invoked
[100%] Built target flash

so openocd, connections and board working right

**Comment by charleskorn** [comment]
Hi @adamvm, like I said, I'm not actively maintaining this any more - if you are able to determine what the issue is, I'd be happy to accept a PR to fix it.
